### PR TITLE
docs: add certificate generation guide

### PR DESCRIPTION
**Pull request by garlicNova**
### Summary

Adds a user guide for certificate generation with the transitioned functions.

### Type

- [ ] Bugfix
- [ ] Enhancement or Feature
- [ ] Code Style or Formatting
- [X] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### Test and Documentation

- [x] Tests have been completed.
- [X] Documentation has been added or updated.

### CODE REVIEW

**Review by tenthirtyam — COMMENTED** [review]
Thanks, Kevin. I'll review when I'm back from PTO and add any formatting I notice. Thank you!

**Comment by bhumitra** [comment]
@garlicNova can you please update the `mkdocs.yml` file with links to the new .md files you have created.

**Comment by bhumitra** [comment]
@garlicNova Please fix the formatting of the page with the links. 
it renders like this currently - 
image

**Comment by tenthirtyam** [comment]
I'll take care of the formatting when I review as well.

**Comment by tenthirtyam** [comment]
I've force-pushed some updates during some time today to clean it up. I have a couple minor items to add to make the tables more readable using some of the MkDocs Material options. Will share when that's ready, but in the meantime, feel free to review again.

**Review by tenthirtyam — APPROVED** [review]

**Pull request merged**
